command_timeout = 1000
palette = "horizon"

[palettes.horizon]
pink = "#ee64ac"
green = "#29d398"
cyan = "#26bbd9"
purple = "#B877DB"
orange = "#fab795"
text = "#e5e5e5"
muted = "#6c6f93"

format = "$directory$git_branch$git_status$python$rust$character"

[directory]
style = "bold cyan"
read_only = " \uf023"
truncate_to_repo = true

[git_branch]
symbol = "\uf418 "
style = "purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "purple"
format = '([\[$all_status$ahead_behind\]]($style) )'
untracked = "[\uea7f](purple)"
modified = "[\uf0ad](purple)"
staged = "[\uf06b](purple)"
deleted = "[\uf1f8](purple)"

[python]
symbol = "\ue73c "
style = "green"
format = 'via [$symbol${version}( \($virtualenv\))]($style) '

[rust]
symbol = "\ue7a8 "
style = "pink"
format = 'via [$symbol$version]($style) '

[character]
success_symbol = "[❯](pink)"
error_symbol = "[❯](red)"

[package]
disabled = true
